# in docker-compose.yaml
version: "3.3"  

services:
  frontend:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    networks:
      - front-tier
      - back-tier
    environment:
      PGRST_DB_URI: "postgres://postgres:1234@db:5432/postgres"
      PGRST_DB_ANON_ROLE: "web_anon"
      PGRST_JWT_SECRET: "1234"
      PGRST_SERVER_PORT: "3000"
      PGRST_DB_SCHEMAS: "api"

  db:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - back-tier
    environment:
      POSTGRES_PASSWORD: "1234"

networks:
  front-tier: {}
  back-tier: {}